# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:11

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
              
      - run: npm install
      - run: npm test

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
          machine:
            services:
              - docker
          
          dependencies:
            cache_directories:
              - ~/docker
          
          deployment:
            staging:
              branch: master
              commands:
                # leallit + docker leklonozod az uj img, es elinditod -> push heroku 
                - docker stop balazsbarni/socket
                - docker pull balazsbarni/socket:latest
                - docker build --rm=false -t registry.heroku.com/balazsbarni/socket/web .
                - docker push registry.heroku.com/balazsbarni/socket/web:latest
                # - docker login --email=$HEROKU_LOGIN --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com